
.PATH: ${LUAB_SRCTOP}/types/sys/stat

# atomic data types
SRCS+=  luab_blkcnt_type.c
SRCS+=  luab_dev_type.c
SRCS+=  luab_fflags_type.c
SRCS+=  luab_ino_type.c
SRCS+=  luab_nlink_type.c

# composite data types
SRCS+=  luab_stat_type.c
