
.PATH:  ${LUAB_SRCTOP}/modules/sys

SRCS+=  luab_sys_dirent.c
SRCS+=  luab_sys_file.c
SRCS+=  luab_sys_ipc.c
SRCS+=	luab_sys_jail.c
SRCS+=  luab_sys_mount.c
SRCS+=  luab_sys_stat.c
SRCS+=  luab_sys_time.c
SRCS+=  luab_sys_timespec.c
SRCS+=  luab_sys_uio.c
SRCS+=  luab_sys_un.c
SRCS+=  luab_sys_unistd.c
SRCS+=  luab_sys_reboot.c
SRCS+=  luab_sys_sched.c
SRCS+=  luab_sys_signal.c
SRCS+=  luab_sys_socket.c
SRCS+=  luab_sys_stdint.c
