
.PATH: ${LUAB_SRCTOP}/udata

SRCS+=	luab_bintime_type.c
SRCS+=	luab_clockinfo_type.c
SRCS+=	luab_crypt_data_type.c
SRCS+=	luab_flock_type.c
SRCS+=	luab_in_addr_type.c
SRCS+=	luab_in6_addr_type.c
SRCS+=	luab_iovec_type.c
SRCS+=	luab_itimerval_type.c
SRCS+=	luab_stat_type.c
SRCS+=	luab_timespec_type.c
SRCS+=	luab_timezone_type.c
SRCS+=	luab_tm_type.c
