
.PATH:  ${LUAB_SRCTOP}/types/sys/socket	

# composite data types
SRCS+=  luab_linger_type.c
SRCS+=  luab_sockaddr_type.c
SRCS+=  luab_msghdr_type.c
SRCS+=  luab_accept_filter_arg_type.c
SRCS+=  luab_cmsgcred_type.c
SRCS+=  luab_sockproto_type.c
SRCS+=  luab_sf_hdtr_type.c
