

.include "${LUAB_SRCTOP}/types/sys/dirent/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/jail/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/mount/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/signal/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/socket/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/stat/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/stdint/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/time/Makefile.inc"
.include "${LUAB_SRCTOP}/types/sys/uio/Makefile.inc"
