
.PATH: ${LUAB_SRCTOP}/atomic

SRCS+=  luab_char_type.c
SRCS+=  luab_ushrt_type.c
SRCS+=  luab_uint_type.c
SRCS+=  luab_int_type.c
SRCS+=  luab_wchar_type.c

SRCS+=  luab_fpos_type.c
SRCS+=  luab_gid_type.c
SRCS+=  luab_off_type.c
SRCS+=  luab_socklen_type.c
SRCS+=  luab_uid_type.c

SRCS+=  luab_double_type.c
SRCS+=  luab_float_type.c
