
.PATH:  ${LUAB_SRCTOP}/core

SRCS+=  luab_core.c
SRCS+=  luab_core_buf.c
SRCS+=  luab_core_lib.c
SRCS+=  luab_core_param.c

SRCS+=  luab_core_table.c
SRCS+=  luab_core_udata.c
SRCS+=  luab_core_iovec.c

