
.PATH:  ${LUAB_SRCTOP}/core

SRCS+=  luab_core.c
SRCS+=  luab_core_buf.c

SRCS+=  luab_core_env.c
SRCS+=  luab_core_modules.c
SRCS+=  luab_core_types.c

SRCS+=  luab_core_atomic.c
SRCS+=  luab_core_lib.c

SRCS+=  luab_core_table.c
SRCS+=  luab_core_udata.c
SRCS+=  luab_core_iovec.c
