
.PATH:  ${LUAB_SRCTOP}/types/pthread

# reference data types
SRCS+=  luab_pthread_type.c
SRCS+=  luab_pthread_attr_type.c
SRCS+=  luab_pthread_mutex_type.c
SRCS+=  luab_pthread_mutexattr_type.c
SRCS+=  luab_pthread_cond_type.c
SRCS+=  luab_pthread_condattr_type.c
SRCS+=  luab_pthread_key_type.c
SRCS+=  luab_pthread_once_type.c

