
.PATH:  ${LUAB_SRCTOP}/types/sys/time	

# composite data types
SRCS+=  luab_bintime_type.c
SRCS+=  luab_clockinfo_type.c
SRCS+=  luab_itimerval_type.c
SRCS+=  luab_timespec_type.c
SRCS+=  luab_timeval_type.c
SRCS+=  luab_timezone_type.c
